# Generated by Django 3.0.7 on 2020-06-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phdtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('thesis_title', models.CharField(max_length=300)),
                ('submission_year', models.IntegerField()),
            ],
        ),
    ]
